### ISSUE TITLE
Deploy to Domain

### ISSUE THREAD

**Issue by wavemaster447** [jnbli/Gmail-Draft-Duplicator#26]
I'm new to Apps Script but I'm trying to deploy this as an Add-On to my (small) domain via the Marketplace.  It's published privately inside the domain, not publicly.  I'm able to get it published correctly as best I can tell, but when I install the add-on from the Marketplace it doesn't seem to work.  It installs successfully, appears in the side bar, but then it gives this error in the side bar:

![image](https://user-images.githubusercontent.com/5333507/104071449-342b3f00-51d7-11eb-90f8-59353e67a4e1.png)

I can deploy the addon via manifest from the Apps Script editor without issue, it's just installing via the marketplace that seems to break things.  Do you have any idea where I would start troubleshooting?

**Comment by JessHua159** [comment]
I apologize for this inconvenience, but we have not gotten this add-on published onto G-suite yet. This is why you are having an issue with installing the add-on from the marketplace.

**Comment by wavemaster447** [comment]
Understood.  It is working fine via the method you suggested but sharing the App Script and directing users to install the development add-on is very clunky.  I'll do some more digging around.
